name: Python Tests

on:
  push:
    branches: main
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}

jobs:
  build:
    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, Wagtail ${{ matrix.wagtail-version }}
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: wagtail_factories
          POSTGRES_DB: wagtail_factories
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        django-version: ["3.2", "4.1", "4.2"]
        wagtail-version: ["4.1", "4.2", "5.0"]
        factoryboy-version: ["3.2"]
        exclude:
          - python-version: "3.7"
            django-version: "4.1"
          - python-version: "3.6"
            django-version: "4.2"
          - python-version: "3.7"
            django-version: "4.2"

          - django-version: "4.0"
            wagtail-version: "5.0"

          - django-version: "4.2"
            wagtail-version: "4.1"
          - django-version: "4.2"
            wagtail-version: "4.2"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox tox-gh-actions
    - name: Test with tox
      env:
        TEST_DB_NAME: wagtail_factories
        TEST_DB_USER: wagtail_factories
        TEST_DB_PASSWORD: secret
        DJANGO: ${{ matrix.django-version }}
        WAGTAIL: ${{ matrix.wagtail-version }}
        FACTORYBOY: ${{ matrix.factoryboy-version }}
      run: |
        tox
